export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'

//AUTH
export const LOG_IN = 'LOGIN'
export const PARTNER_REGISTER = 'PARTNER_REGISTER'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const CHECK_PHONE_EXIST = 'CHECK_PHONE_EXIST'
export const LOG_OUT = 'LOG_OUT'
export const CREATE_INSTALLATION = 'CREATE_INSTALLATION'
export const DELETE_INSTALLATION = 'DELETE_INSTALLATION'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_USER_KYC = 'UPDATE_USER_KYC'

export const GET_ORDER = 'GET_ORDER'
