export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'

//AUTH
export const LOG_IN = 'LOGIN'
export const PARTNER_REGISTER = 'PARTNER_REGISTER'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const CHECK_PHONE_EXIST = 'CHECK_PHONE_EXIST'
export const LOG_OUT = 'LOG_OUT'
export const CREATE_INSTALLATION = 'CREATE_INSTALLATION'
export const DELETE_INSTALLATION = 'DELETE_INSTALLATION'

export const CONNECT_SOCKET = 'CONNECT_SOCKET'
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_USER_KYC = 'UPDATE_USER_KYC'

export const GET_ORDER = 'GET_ORDER'
export const APPLICANT_ORDER = 'APPLICANT_ORDER'
export const CANCEL_APPLICANT = 'CANCEL_APPLICANT'

export const GET_APPOINTMENT = 'GET_APPOINTMENT'
export const GET_APPOINTMENT_IN_PROGRESS = 'GET_APPOINTMENT_IN_PROGRESS'
export const GET_APPOINTMENT_BY_ID = 'GET_APPOINTMENT_BY_ID'
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'
export const UPDATE_COMPLETE_APPOINTMENT = 'UPDATE_COMPLETE_APPOINTMENT'

export const GET_CHAT_BY_APPLICANT = 'GET_CHAT_BY_APPLICANT'
export const SEND_MESSAGE = 'SEND_MESSAGE'

export const UPDATE_SETTING = 'UPDATE_SETTING'
export const UPDATE_LOCATION_PARTNER = 'UPDATE_LOCATION_PARTNER'

export const CREATE_QR_PAID = 'CREATE_QR_PAID'
export const CREATE_QR_TOP_UP = 'CREATE_QR_TOP_UP'
export const CREATE_REQUEST_WITH_DRAW = 'CREATE_REQUEST_WITH_DRAW'
export const TOP_UP = 'TOP_UP'

export const GET_HISTORY_TRANSACTION = 'GET_HISTORY_TRANSACTION'
export const GET_RATE = 'GET_RATE'
